### ISSUE TITLE
Regarding TAIR10.ideogram

### ISSUE THREAD

**Issue by wyim-pgl** [xie186/ICME#1]
Dear Shaojun Xie,
Hello,
Can you please share TAIR10.ideogram file format?
I cannot find it.

Thanks.

**Comment by xie186** [comment]
Sorry for the late response. Just saw this issue. In case you're still interested in, here is the file:
https://github.com/xie186/MutFinder/blob/master/TAIR10_chr_all.ideogram
Best,
Shaojun

**Comment by wyim-pgl** [comment]
Thanks
